language: node_js
node_js:
  - 'node'

script: NODE_ENV=production yarn build

before_deploy:
  - shopt -s extglob
  - rm -rf !(dist|index.html|manifest.json)

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN

branches:
  only:
    - master
