language: node_js
node_js:
  - 'node'

cache: yarn

script: NODE_ENV=production yarn build

before_deploy:
  - find . -mindepth 1 -maxdepth 1 -not \( -name 'dist' -or -name 'favicons' -or -name 'index.html' -or -name 'manifest.json' \) -print0 | xargs -0 rm -rf

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN

branches:
  only:
    - master
